#language: cpp
language: python
python:
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements.txt
branches:
  only:
    - master

before_script: ls

#compiler:
#  - g++

script:
#  - g++ src/main.cpp -o h
  - ./scrape.py