language: R
R:
  - "3.5"
addons:
  - echo "add ons here"
before_install:
  - mkdir -p data/test
  - cd data/test
  - echo "Neo4j" > config.txt
install:
  - echo "installation here"
before_script:
  - ls
  - sleep 3
script:
  - ../../code/script.R
