language: R
R:
  - "3.5"
r_packages:
  - ggplot2
  - readr
cache: packages
addons:
  - echo "add ons here"
before_install:
  - mkdir -p data/test
  - cd data/test
  - echo "Neo4j" > config.txt
install:
  - echo "installation here"
before_script:
  - ls
  - Rscript -e 'install.packages("ggplot2",repos="http://cran.us.r-project.org")'
  - Rscript -e 'install.packages("readr",repos="http://cran.us.r-project.org")'
script:
  - ../../code/script.sh
after_script:
  -ls