#language: cpp
sudo: required
dist: "trusty"
language: python3
addons:
  - firefox: "56.0.2"
  - apt:
    packages:
      - "python3"
      - "python3-pip"
#python:
#    - "3.6"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - sudo pip3 install --upgrade pip3
  - sudo pip3 install selenium

branches:
  only:
    - master

before_script: ls

#compiler:
#  - g++

script:
#  - g++ src/main.cpp -o h
  - ./scrape.py
